---
- name: Playbook to install generic tools
  hosts: pvt
  gather_facts: yes
  become: yes
  vars:
    TFROM: 1.8.5
  tasks:
    - name: Check the hostnames
      command: cat /etc/lsb-release
      register: hostname_output
    - name: Display hostname information
      debug:
        var: hostname_output.stdout

    - name: Perform apt update
      apt:
        update_cache: yes

    - name: Install tools
      apt:
        name:
          - unzip
          - jq
          - stress
          - net-tools
        state: present
        upgrade: yes
